// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB03bBQBtTzuWISn_BJlx0M6JzPZ4ItpIs',
    appId: '1:779498011977:web:b2cd7d04811ed60bceee98',
    messagingSenderId: '779498011977',
    projectId: 'my-project-6f4c8',
    authDomain: 'my-project-6f4c8.firebaseapp.com',
    storageBucket: 'my-project-6f4c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4J4V1f9YUCI4Xj0ZmaD69FiibpVJ21Ww',
    appId: '1:779498011977:android:ed055c19d2eee3c4ceee98',
    messagingSenderId: '779498011977',
    projectId: 'my-project-6f4c8',
    storageBucket: 'my-project-6f4c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ66Hwtl3mG9vqiVZE1M1WsbKchQNhVtQ',
    appId: '1:779498011977:ios:89dacd009b90cb09ceee98',
    messagingSenderId: '779498011977',
    projectId: 'my-project-6f4c8',
    storageBucket: 'my-project-6f4c8.appspot.com',
    iosClientId: '779498011977-sjeie35o8pge4pnodv818u5tru38cpiu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ66Hwtl3mG9vqiVZE1M1WsbKchQNhVtQ',
    appId: '1:779498011977:ios:89dacd009b90cb09ceee98',
    messagingSenderId: '779498011977',
    projectId: 'my-project-6f4c8',
    storageBucket: 'my-project-6f4c8.appspot.com',
    iosClientId: '779498011977-sjeie35o8pge4pnodv818u5tru38cpiu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynote',
  );
}
